name:                cofree-coffee-cast
version:             0.1.0.0
github:              "isovector/cofree-coffee-cast"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/cofree-coffee-cast#readme>

dependencies:
- base >= 4.7 && < 5
- slick
- aeson
- pandoc
- shake
- text
- lens-aeson
- lens

executables:
  cofree-coffee-cast:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
